[statmetric-influx-encoder]
type = "SandboxEncoder"
filename = "lua_encoders/statmetric_influx.lua"

[influx]
type = "HttpOutput"
message_matcher = "Type == 'heka.statmetric'"
address = "http://$(heka.influxdb.host):8086/db/$(heka.influxdb.dbname)/series"
encoder = "statmetric-influx-encoder"
username = "$(heka.influxdb.user)"
password = "$(heka.influxdb.password)"

